# 
# Decompression application using adaptive arithmetic coding
# 
# Usage: python adaptive-arithmetic-decompress.py InputFile OutputFile
# This decompresses files generated by the adaptive-arithmetic-compress.py application.
# 
# Copyright (c) Project Nayuki
# 
# https://www.nayuki.io/page/reference-arithmetic-coding
# https://github.com/nayuki/Reference-arithmetic-coding
# 

import os
import sys
import torch
import numpy as np
from codes.AE import arithmeticcoding
from nets import entropy

verbose = False
cc_decompress = None

python3 = sys.version_info.major >= 3


# Command line main application function.
def main(args):
    # Handle command line arguments
    if len(args) != 2:
        sys.exit("Usage: python adaptive-arithmetic-decompress.py InputFile OutputFile")
    inputfile, outputfile = args

    # Perform file decompression
    with open(inputfile, "rb") as inp, open(outputfile, "wb") as out:
        bitin = arithmeticcoding.BitInputStream(inp)
        decompress(bitin, out)


"""
def decompress(bitin, out):
    initfreqs = arithmeticcoding.FlatFrequencyTable(257)
    freqs = arithmeticcoding.SimpleFrequencyTable(initfreqs)
    dec = arithmeticcoding.ArithmeticDecoder(32, bitin)
    while True:
        # Decode and write one byte
        symbol = dec.read(freqs)
        if symbol == 256:  # EOF symbol
            break
        out.write(bytes((symbol,)) if python3 else chr(symbol))
        freqs.increment(symbol)
"""


def read_bytes(bitin):
    ret = 0
    for i in range(8):
        x = bitin.read()
        ret = (ret << 1) | x
    return ret


def read_int(bitin, bytes):
    if not isinstance(bitin, arithmeticcoding.BitInputStream):
        assert 0
    ret = 0
    a = []
    for i in range(bytes):
        a.append(read_bytes(bitin))
    a = list(reversed(a))
    for i in range(bytes):
        ret = (ret << 8) | a[i]
    return ret


def get_shape(bitin):
    shape_len = read_int(bitin, 1)
    shape = []
    for i in range(shape_len):
        shape.append(read_int(bitin, 2))
    return shape, 1 + 2 * shape_len


def to_prob_table_min_max(_min, _max, _shape, entropy_model, device, scale_factor=1, pre_channel=True):
    channel = _shape[1] if pre_channel else 1
    n = _shape[1] * _shape[2] * _shape[3]
    y_range = np.array([list(range(_min, _max + 1))] * channel) \
        .reshape([1, channel, 1, -1])
    y_range_rescaled = y_range / scale_factor
    with torch.no_grad():
        temp = torch.tensor(y_range_rescaled, device=device).float()
        if verbose:
            print(temp.shape)
        prob = entropy_model(temp).cpu().numpy()
        prob *= n
        prob[prob < 1] = 1
        prob = np.round(prob).astype(int)

    assert prob.shape == y_range.shape
    y_range = y_range.reshape([channel, -1])
    prob = prob.reshape([channel, -1])

    table_len = _max - _min + 2
    table = []
    for c in range(channel):
        sub_table = [1] * table_len
        for v, p in zip(y_range[c], prob[c]):
            sub_table[v - _min] = p
        table.append(sub_table)
    return table


def get_table(_min, _max, _shape, log_dir='../experiments/GG/logs', epoch=2000):
    def _remove_dist_module_prefix(k: str):
        return k[7:] if k.startswith('module.') else k

    entropy_pre = entropy.Entropy_Bottleneck(input_channels=_shape[1])
    ckpt = torch.load(os.path.join(log_dir, 'entropy_pre_epoch-{}.pth'.format(epoch)), map_location='cpu')
    ckpt = {_remove_dist_module_prefix(k): v for k, v in ckpt.items()}
    entropy_pre.load_state_dict(ckpt)
    print("decompress: loaded entropy_model, epoch: {}".format(epoch))
    return to_prob_table_min_max(_min, _max, _shape, entropy_pre, 1, True)


# file_name :string(file to be decompressed)
# return x :numpy array(data before compressing)
def decompress(file_name, per_channel, adapt=True, use_table=False, prob_table=None):
    x = []
    with open(file_name, "rb") as inp:
        bitin = arithmeticcoding.BitInputStream(inp)
        shape, _ = get_shape(bitin)
        table_len = read_int(bitin, 2)
        x_min = read_int(bitin, 2)
        if x_min > 32767:
            x_min -= 65536
        print("decompressing!!  shape: {}".format(shape), table_len, x_min)
        channel = shape[1] if per_channel else 1
        if use_table:
            if prob_table is None:
                prob_table = get_table(x_min, table_len + x_min - 2, shape)
            assert channel == len(prob_table)

        dec = arithmeticcoding.ArithmeticDecoder(32, bitin)

        for c in range(channel):
            if use_table:
                initfreqs = arithmeticcoding.EntropyFrequencyTable(table_len, prob_table[c])
            else:
                initfreqs = arithmeticcoding.FlatFrequencyTable(table_len)
            freqs = arithmeticcoding.SimpleFrequencyTable(initfreqs)

            while True:
                symbol = dec.read(freqs)
                if symbol == table_len - 1:  # EOF symbol
                    break
                # out.write(bytes((symbol,)) if python3 else chr(symbol))
                x.append(symbol)
                if adapt:
                    freqs.increment(symbol)
    return np.array(x).reshape(shape) + x_min


def decompress_with_index(file_name, index, adapt=True, prob_table=None, backend='py'):
    """
    :param file_name:
    :param index: code shaped array or a callable (min, table_len, shape) => index
    :param adapt:
    :param prob_table: 2D array or a callable (min, table_len, shape) => table.
    If None, use a flatten table (with all symbols having same frequencies)
    :return:
    """
    with open(file_name, "rb") as inp:
        bitin = arithmeticcoding.BitInputStream(inp)
        shape, num_read = get_shape(bitin)
        table_len = read_int(bitin, 2)
        x_min = read_int(bitin, 2)
    offset = num_read + 2 + 2

    if x_min > 32767:
        x_min -= 65536
    print("decompressing!!  shape: {}".format(shape), table_len, x_min)

    if callable(index):
        index = index(x_min, table_len, shape)

    index = np.array(index)
    assert tuple(shape) == index.shape
    index = index.flatten()

    if callable(prob_table):
        prob_table = prob_table(x_min, table_len, shape)

    if backend == 'py':
        x = _decompress_py(file_name, index, prob_table, table_len, offset, adapt)
    elif backend == 'cc':
        global cc_decompress
        if cc_decompress is None:
            from codes.cc.ae_cc_interface import cc_decompress
        x = cc_decompress(file_name, prob_table, index, adapt, offset)
    else:
        raise ValueError('unsupported decompress backend "{}"'.format(backend))

    return np.array(x).reshape(shape) + x_min


def _decompress_py(file_name, index, prob_table, table_len, offset, adapt):
    with open(file_name, "rb") as inp:
        bitin = arithmeticcoding.BitInputStream(inp)
        read_int(bitin, offset)
        if prob_table is not None:
            prob_table = np.array(prob_table, dtype=int)
            assert prob_table.ndim == 2
            assert index.max() < prob_table.shape[0]
            assert table_len == prob_table.shape[1]
            initfreqs = [arithmeticcoding.EntropyFrequencyTable(table_len, pt) for pt in prob_table]
        else:
            initfreqs = [arithmeticcoding.FlatFrequencyTable(table_len)]
        freqs = [arithmeticcoding.SimpleFrequencyTable(f) for f in initfreqs]

        x = []
        dec = arithmeticcoding.ArithmeticDecoder(32, bitin)
        for ind in index:
            symbol = dec.read(freqs[ind])
            if symbol == table_len - 1:  # EOF symbol
                raise EOFError('met unexpected terminal symbol')
            x.append(symbol)
            if adapt:
                freqs[ind].increment(symbol)
        symbol = dec.read(freqs[0])
    assert symbol == table_len - 1
    return x


# Main launcher
if __name__ == "__main__":
    # main(sys.argv[1 : ])
    x = decompress("test.bin", False)
    print(x)

    x = decompress("test2.bin", False)
    print(x)

    x_size = 10
    prob = {'0': 0.3, '1': 0.5, '2': 0.1, '3': 0, '4': 0, '5': 0.1, '6': 0}
    for k in prob:
        prob[k] *= 10
    prob_table = list(prob.values())
    prob_table = [round(f) for f in prob_table]
    prob_table = [1 if f == 0 else f for f in prob_table]
    print(prob_table)
    x = decompress("test3.bin", False, use_table=True, prob_table=[prob_table])
    print(x)
    x = decompress("test4.bin", False, adapt=False, use_table=True, prob_table=[prob_table])
    print(x)

    # use table
    prob1 = {'0': 0.3, '1': 0.5, '2': 0.1, '3': 0, '4': 0, '5': 0.1, '6': 0}
    prob2 = {'0': 0.6, '1': 0.7, '2': 0.8, '3': 0.2, '4': 0.3, '5': 0.9, '6': 0}
    prob_table = []
    for prob in [prob1, prob2]:
        for k in prob:
            prob[k] *= x.size // 2
        _prob_table = list(prob.values())
        _prob_table = [round(f) for f in _prob_table]
        _prob_table = [1 if f == 0 else f for f in _prob_table]
        prob_table.append(_prob_table)
    x = decompress("test5.bin", True, adapt=False, use_table=True, prob_table=prob_table)
    print(x)
    x = decompress("test6.bin", True, adapt=True, use_table=True, prob_table=prob_table)
    print(x)

    # test decompress_with_index

    prob_table = [[1, 3, 2, 4, 2, 4, 1], [1, 56435, 343, 5, 2, 3, 5], [122, 21, 2, 2, 442, 2, 4]]
    index = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]).reshape([1, 3, 2, 2])
    # index = [0, 1, 2, 2, 1, 0, 0, 1, 2, 0, 1, 2]
    expected = np.array([1, 2, 3, 4, 5, 6, 1, 3, 5, 2, 4, 6]).reshape([1, 3, 2, 2])
    actual = decompress('compress_test.bin', True, False, True, prob_table)
    assert (actual == expected).all()


    def per_channel_idx_fn(_min, _table_len, shape):
        c, w, h = shape[1:]
        index = np.arange(c, dtype=int).repeat(w * h).reshape(shape)
        return index


    actual = decompress_with_index('compress_test_with_index.bin', per_channel_idx_fn, False, prob_table)
    assert (actual == expected).all()

    actual = decompress_with_index('compress_test_with_index.bin', index, False, prob_table)
    assert (actual == expected).all()


    def get_table(min, len, shape):
        prob_table = [[33, 1, 3, 2, 4, 2, 4, 1, 44][min:min + len],
                      [33, 1, 56435, 343, 5, 2, 3, 5, 44][min:min + len],
                      [33, 122, 21, 2, 2, 442, 2, 4, 44][min:min + len]]
        return prob_table


    actual = decompress_with_index('compress_test_with_index.bin', index, False, get_table)
    assert (actual == expected).all()
